<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignment_1" nsURI="http://www.example.org/assignment_1" nsPrefix="assignment_1">
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CourseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CourseCredit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CourseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StudentNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumberOfSemesters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseStatus">
    <eLiterals name="O"/>
    <eLiterals name="VA" value="1"/>
    <eLiterals name="VB" value="2"/>
    <eLiterals name="M1A" value="3"/>
    <eLiterals name="M2A" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization"/>
</ecore:EPackage>
